### ISSUE TITLE
CI einrichten

### ISSUE THREAD

**Issue by FrankR85** [fiduciagad/connected-n#1]
Als Entwickler möchte ich, dass bei jedem Commit automatisch der Build getriggert wird und ich über die Ergebnisse informiert werde.

--> TravisCI einrichten.

**Comment by pfichtner** [comment]
done

**Comment by FrankR85** [comment]
Mir ist auf Anhieb nicht klar, woran es liegt, aber scheinbar werden bei Travis nicht alle Testfälle ausgeführt.
Der ```UdpServerRealTournamentIT``` fehlt z.Bsp..

Die Integrationstests ```*IT.java``` im ```core```-Module werden ausgeführt, aber die aus dem ```udp```-Modul scheinbar nicht.
