### ISSUE TITLE
Antwort auf REGISTER fehlt in Protokollbeschreibung

### ISSUE THREAD

**Issue by mmitch** [fiduciagad/connected-n#16]
Ich hatte meinen Client nach der Beschreibung implementiert und beim ersten echten Test habe ich dann gemerkt, dass eine Antwort auf REGISTER zurückkommt. Diese Antwort ist in der README.md nicht beschrieben.

**Comment by mmitch** [comment]
ping @FrankR85 - abonnier hier mal ;-)

**Comment by pfichtner** [comment]
Fixed by 08278ee70306614195f7e53493629c8d5d570b74
