### ISSUE TITLE
Antwort auf REGISTER passt nicht zum Rest des Protokolls

### ISSUE THREAD

**Issue by mmitch** [fiduciagad/connected-n#17]
Das gesamte Protokoll ist in der Form
```
BEFEHL[;parameter[;parameter[;parameter[…]]]
```

Die Antwort auf `REGISTER;mein-name` lautet aber nicht `WELCOME;mein-name`, sondern `Welcome mein-name`.
Das ist inkonsistent und erschwert es, einen Client zu schreiben, weil man keinen generischen Parser für die Form `BEFEHL[;parameter[;parameter;[…]]` benutzen kann.
Vermutlich ist das wegen #16 noch nicht aufgefallen.

Lässt sich das noch ändern oder ist das Protokoll schon komplett festgezurrt?

**Comment by mmitch** [comment]
paging Dr. @FrankR85

**Comment by pfichtner** [comment]
Fixed by 08278ee70306614195f7e53493629c8d5d570b74

**Comment by pfichtner** [comment]
Sorry, closed wrong issue

**Comment by pfichtner** [comment]
Response on REGISTER command changed with 6812d5b0511dcdf93de59fcf4728ba515d240742 from "Welcome " to "WELCOME:"

**Comment by mmitch** [comment]
Moment: Wieso Doppelpunkt?
Alles ander hat da ein Semikolon.

**Comment by pfichtner** [comment]
Issues um eins nachts fixen ist wohl doch nicht ideal! ;-)
fixed with 95a8ba9e4df005c447119e96a2487c8ab6d66fcb
