### ISSUE TITLE
Start-Stop-Schalter in Server einbauen

### ISSUE THREAD

**Issue by mmitch** [fiduciagad/connected-n#22]
Als Turnierleitung möchte ich sicherstellen, dass alle Clients gleichzeitig anfangen und auch gleichzeitig aufhören, damit eine gerechte Punktezählung möglich ist.

In der aktuellen Implementierung haben diejenigen einen Vorteil, die
- sich zuerst am Server anmelden und schon ein paar Seasons Vorsprung haben, bevor der Rest dazu kommt
- bei Serverstop in der zuletzt letzten Season am Anfang dran waren (der Rest der Season wird nicht mehr gespielt)

Mögliche Implementierung:
Ein von außen steuerbarer Schalter, der beim Start einer Season abgefragt wird. Ist er nicht gesetzt, können sich Clients am Server (de)registrieren, aber der `SEASON START` wird so lange verzögert, bis der Schalter aktiviert wird.
Umgekehrt läuft nach Deaktivierung des Schalters die aktuelle Season noch zu Ende, danach wird aber erstmal keine neue Season mehr gestartet.

Parallel dazu sollte das alte Verhalten (fliegender Start/kein Schalter) weiterhin verfügbar sein, um die Turniervorbereitung (das allgemeine Hacken der Teilnehmer gegen einen laufenden Server) sowie die generelle Entwicklung von Server und Clients nicht zu verkomplizieren.

**Comment by pfichtner** [comment]
Ich sehe das Problem hauptsächlich beim Stoppen, den Start hat man ja in eigener Hand oder sehe ich das falsch? 
Für das Stoppen würde mir würde einfallen: 

- Magisches UDP-Paket: Der Server schreibt beim Start auf die Konsole eine Admin-UUID mit dieser kann man den Stop Befehl z.B. via netcat senden. Admin-UUID sollte ntürlich kein Teilnehmer auf dem Beamer sehen, Alternative wäre noch schreiben in eine Datei
- Server stoppt  nach dem EPmfang von Signal, z.B. USR1

@mmitch @FrankR85 Was meint ihr dazu? Habt ihr weitere Ideen?

**Comment by mmitch** [comment]
Beim Starten geht es auch schief, da sich die Clients erst nach Server-Start connecten können.

Sobald zwei Clients da sind, startet soweit ich weiß die erste Season (worauf auch sonst noch warten?), alle anderen Clients haben die erste Season verpasst.

Da führt dann zu "wild auf Enter hacken, sobald der Server da ist". Wer seinen Bot zu früh startet, schickt sein `REGISTER` ins Nirvana und spielt gar nicht mit.

Gut, man könnte die Clients animieren, alle eine Schleife zu bauen, um sich so lange zu registrieren, bis ein `WELCOME` kommt, aber wenn sich da die Pakete überholen, spielen Client und Server `REGISTER`-`WELCOME`-Ping-Pong :-)

Wie gut Signale auf Windows funktionieren, weiß ich nicht, ansonsten klingt das nach einer guten Idee.
Magisches Paket würde auch funktionieren. Selbst falls das wer vom Beamer schnell abtippt, fällt das ja auf.
Vom Ablauf her würde ich vorschlagen:
* initial passiert gar nichts, Server verhält sich wie jetzt
* dann kann man per Paket oder Signal die "Bremse" anschalten, ab jetzt starten keine neuen Seasons mehr
* sobald alle registriert sind, per Paket oder Signal die "Bremse" wieder lösen
Der Admin kriegt das schon hin, den Server zu starten und danach gleich die Bremse anzumachen. Wird ja nur im finalen Turnier benötigt.

**Comment by FrankR85** [comment]
Denke auch, dass es hauptsächlich beim Start ein Problem ist. 
Der Mäxchen-Server hat auch so einen [Start-Schalter](https://github.com/conradthukral/maexchen/blob/master/server/lib/index.coffee#L9).

**Comment by pfichtner** [comment]
Über die Umgebungsvariable DELAY kann eine Startverzögerung gesetzt werden (identisches Verhalten wie beim Mäxchen Server). Gestoppt werden kann der Server ganz normal mit CTRL+C, dabei wird die laufende Saison aber noch fertig gespielt. 
Issue wird geschlossen, bitte wieder aufmachen falls nicht ok

**Comment by mmitch** [comment]
Passt!
Das Fertigspielen der Season nach SIGINT ist auch nett.
