### ISSUE TITLE
Automatische Deregistrierung von Clients nach mehreren Timeouts

### ISSUE THREAD

**Issue by mmitch** [fiduciagad/connected-n#23]
Nicht erreichbare Clients sollen nach einer Zeit automatisch degistriert werden, damit nicht immer und immer wieder in die entsprechenden Timeouts gelaufen wird.

Mögliche Implementierung wäre ein Timeout-Zähler pro Client:
* bei jeder pünktlich empfangenen Nachricht des Clients wird der Zähler auf 0 gesetzt
* bei jedem Timeout des Clients wird der Zähler um 1 erhöht
* bei Erreichen eines bestimmten Zählerstandes (z.B. 3 Timeouts am Stück) wird der Client deregistriert

offen:
* jede Nachricht für den Timer berücksichtigen oder nur den `SEASON START`?
* macht das Zurück- bzw. Hochsetzen des Zählers ggf. nur bei `sendAndWait()` Sinn? wenn eine Nachricht zu spät eintrifft, landet sie zwar verspätet, aber trotzdem noch in der Client-Nachrichten-Queue, dann wäre es nicht sinnvoll, den Timeout-Zähler wieder auf 0 zu setzen – die Nachricht war ja verspätet

Hintergrund:
Im heutigen Turnier hatten wir (vermutlich WLAN-bedingt) größere Latenzen und mussten aus den 250ms Pause ganze 2 Sekunden machen, damit die Clients nicht unverschuldet in Timeouts laufen.
Mit einem so großen Timeout ziehen sich Seasons, in denen 5 registrierte Clients nicht mehr erreichbar sind, extrem in die Länge.
Selbst bei 250ms wirken sich nicht erreichbare Clients schon spürbar aus.

**Comment by FrankR85** [comment]
Dieses Feature wäre auf jeden Fall sinnvoll. 👍 

Aber ob die Seasons nur mit diesem Feature wesentlich schneller werden, würde ich bezweifeln. 
Am Anfang einer Season werden ja alle registrierten Spieler parallel befragt, ob sie joinen wollen. Diese ganze Abfrage dürfte ja maximal `TIMEOUT` Millisekunden dauern.

Nervig sind natürlich halbfertige Clients, die schon eine Season joinen können, aber bei jedem Zug einen Timeout verursachen. 👎 Da würde allerdings dieses Feature hier auch nix helfen...

**Comment by mmitch** [comment]
Deshalb die Variante, das auf die gesamte Kommunikation anzuwenden: 5 Timeouts am Stück und raus.

Man kann natürlich auch einfach nettere Clients programmieren, die ein `DEREGISTER` schicken, wenn sie beendet werden oder abstützen.  
Ich fasse mich da selbst an die Nase, bin bisher noch nicht drauf gekommen – werde ich bei mir demnächst ergänzen.

**Comment by pfichtner** [comment]
Ich werde es so umsetzen, dass wer n timeouts in Folge verursacht raus geschmissen wird

**Comment by pfichtner** [comment]
Mit 0f6456d4151ab43b174db1c3c95922c4c91a3418 werden Clients nach 10 Timeouts in Folge vom Server deregistriert
