### ISSUE TITLE
Probleme mit Player-Queue für UDP-Pakete

### ISSUE THREAD

**Issue by mmitch** [fiduciagad/connected-n#24]
Wir haben heute im langsamen WLAN folgende Fehlerkonstellation beobachtet:

* Client will einen Zug machen
* UDP-Paket verspätet sich
* Client läuft in Timeout, Spielrunde wird beendet
* neue Runde oder Season startet
* Client wird zum neuen Spiel/neuer Season eingeladen:
  + Server macht `sendAndWait()`
  + Server erwartet ein `JOIN`
  + jetzt kommt endlich das verspätete UDP-Paket mit dem letzten Zug des Clients an
  + Server hat kein `JOIN` bekommen und ist verwirrt
  + Client darf nicht mitspielen

Das Protokoll hat sich in den Fall also verheddert, weil es asynchron auseinandergelaufen ist.
Der Server forciert das Problem dadurch, dass er sich pro Client die letzten 10 Pakete in einer Queue merkt – wenn das Paket mit dem Zug nur knapp nach dem Timeout eintrifft, dann lässt der Server es so lange in der Queue, bis er sie das nächste Mal ausliest – was genau dann passiert, wenn er eigentlich auf das `JOIN` wartet.

Unsere Heftpflaster-Schnellösung war, vor der Ankündigung einer neuen Season an den Client erstmal die Queue des Clients zu löschen. Damit reduziert sich die obige Fehlerkonstellation auf Pakete, die tatsächlich noch gerade auf dem Draht unterwegs sind.

Eine sauberere Lösung wäre vermutlich, beim `sendAndWait()` den Typ der erwarteten Nachricht mitzugeben und dann im Player-Code die Queue auszulesen und schon auf den passenden Nachrichtentyp zu filten.
Im obigen Fall hieße das: Wenn noch andere Pakete vor dem `JOIN` in der Queue sind, werden sie überlesen und verworfen und nur das `JOIN` zurückgegeben. Wenn keine passenden Nachrichten da sind, gibt es einen Timeout wie sonst auch.

Das ganze Protokoll ja generell als Ping-Pong zwischen Client und Server aufgebaut: Jede Nachricht des Servers wird mit einer Gegennachricht des Clients beantwortet.  Sobald der Server einmal einen Timeout festgestellt hat (von dem der Client ja nichts weiß und der ein Paket, das bereits "auf dem Kabel" ist, auch nicht mehr bremsen kann), bekommt der Server ab dann bei jedem Auslesen der Nachricht des Clients die Antwort auf seine _vorherige_ Frage, die Kommunikation ist clientseitig dann um eine Nachricht "verrutscht".
Warum gibt es überhaupt die Queue am Client? Ist die die Lösung für andere Probleme?
Dass ein Client die Antwort auf eine Frage losschickt und erstmal in der Queue lagert, bevor der Server die Frage gestellt hat, kann ja eigentlich nicht sein ;-)

**Comment by pfichtner** [comment]
Die Queue habe ich eingeführt, da wir serverseitig das Problem mit dem Verrutschen hatten. Ohne Queue hatte, unter der Konstellation eines verlorenen Antwort vom Client an den Server, der Server das "Offser by one" Problem, d.h. er hat bemängelt: "expected A got B" dann "expected B got C", etc.
Ich muss mir das mit Blick auf beide Seiten nochmal anschauen, falls euch das direkt klar ist gerne entsprechend kommunizieren.

**Comment by pfichtner** [comment]
Ok, Problem erkannt: Wenn der Server auf eine Nachricht wartet, dann eine andere Nachricht eintrifft wartet er nicht mehr, ob innerhalb des Timeouts nicht doch noch die richtige Nachricht eintrifft. Der Server geht aus der Warteschleife, wenn aktuell keine Nachricht mehr da ist (und die Nachricht kommt ja erst kurz darauf)
https://github.com/fiduciagad/connected-n/blob/de357dc975d22d582bf4bf0a9c66ce6c5afc1fc6/udp/src/main/java/org/ase/fourwins/udp/server/UdpServer.java#L78

Ich habe das mal gefixed, allerdings ohne Tests, für all die Probleme hätte ich gerne  Tests welche deterministisch verifizieren ob der Code das tut was er soll, dafür müsste man aber ein wenig umbauen um das Timingverhalten von aussen steuern zu können. 

Hier mein Vorschlag für den Fix: 
https://github.com/fiduciagad/connected-n/blob/88632c53e8bb5e6955ef88f890ddf4895596bb94/udp/src/main/java/org/ase/fourwins/udp/server/UdpServer.java#L71
Ich **vermute** dass man von der Queue weg gehen **könnte**, die Queue hat aber der Vorteil, dass die Abarbeitung erst bei voller Queue ausgebremst wird, falls der Konsument nicht schnell genug ist. Ohne Queue würde die UDP Empfangsseite möglicherweise stärker ausgebremst

**Comment by mmitch** [comment]
Die Queue ist doch pro Client einzeln – wann kann denn der jemals zwei Kommandos auf einmal schicken, dass es sich lohnen würde, die Queue zu halten? Im Zweifelsfall käme ein Kommando aus der Queue, das nicht zur Frage des Servers passt.

Aber vielleicht sorum:  
Frage und Antwort sind ja meist per ID gekoppelt. Man könnte die ja irgendwie einfliessen lassen in der Art "Server hat Anfrage mit ID xyz geschickt, also wird so lange aus der Queue gelesen, bis entweder eine Antwort mit ID xyz da ist oder der Timeout rum ist".  
Dann würden sich eine "Verhedderung" automatisch wieder einrenken, weil der Server überflüssige Pakete auffrisst. Ungefähr das, was wir mit "Queue leeren bei neuer Season" gemacht haben, nur in schlauer und allgemeingültiger.

**Comment by pfichtner** [comment]
...aber genau das macht doch der Patch. Hast Du denn mal reingeschaut? 
Da bei Dir das Problem aufgetreten ist, hätte ich gerne Deine Meinung, ob Du meinst, dass diese Änderung auch Dein Problem vermutlich fixt.

**Comment by FrankR85** [comment]
Meiner Meinung nach _müsste_ der Patch funktionieren.

Der betreffende Code ist allerdings wirklich recht schwierig zu durchschauen. Das `while(true)` macht es nicht besser, allerdings wüßte ich adhoc auch keine bessere Variante.

Gefühlt fehlt der `ArrayBlockingQueue` eine `#isEmpty`-Methode, welcher man einen Timeout mitgeben kann. Würde im Code stehen 
```
while (!responses.isEmptyWithDelay(milliesLeft, MILLISECONDS))
```
wäre es klarer.

**Comment by mmitch** [comment]
@pfichtner  D'oh, ich hab nur die Ein-Zeilen-Änderung der While-Bedingung angeguckt (das, was da inline stand) und nicht den Code drumherum. Nach dem Klick darauf sehe ich jetzt: ach schau, da wird die UUID ja schon geprüft.

Da wir beide unbeeinflusst voneinander zum gleichen Ergebnis gekommen sind: Ja, genau so sollte es funktionieren :-)

@FrankR85 Ich finde das mit dem `while (true)` in Odnung – vielleicht, weil ich zu viel Perl mache: Das ist eine typische Schleife, deren Abbruchbedingung komplizierter ist und "aus Gründen" irgendwo im Bauch der Schleife steht. In so einem Fall ist mMn. `while (true)` genau passend – da weiß man sofort, dass man im Body suchen muss.

**Comment by pfichtner** [comment]
mit PR #25 gefixt
