### ISSUE TITLE
UNREGISTER ist nicht dokumentiert

### ISSUE THREAD

**Issue by mmitch** [fiduciagad/connected-n#26]
Bei der Umsetzung des ordentlichen Abmeldens in https://github.com/mmitch/bash-n/commit/01a06ff7051ad66a71a92dda273c64168695cec4 ist mir aufgefallen, dass `UNREGISTER` gar nicht dokumentiert ist.

Anmerkung:
Ich hatte erst `UNREGISTER;bot-name` versucht, aber anders als `REGISTER` wird der Botname nicht benötigt. Das war zwar unerwartet, aber auch sehr praktisch, denn das spart mir Handstände im UDP-Adapter, der den Botnamen nicht selber kennt und das Protokoll mitlesen müsste :-)  Bitte das ruhig so lassen.

**Comment by pfichtner** [comment]
Das Protokoll wurde von Mäxchen übernommen und adaptiert. Potentiell ist das allerdings eine ausnutzbare Schwachstelle: 

- Das blanke Kommando ermöglich mit gefälschter  src-ip/port das Abmelden eines anderen Bots
- Mit name ebenfalls ;-)

Da dies kein Request/Response ist, kann man auch keine UUID für das Kommando einführen

@FrankR85 @mmitch Eure Meinung? 
Da sich vermutlich selten ein Client abmeldet und #23 gelöst ist, würde ich das UNREGISTER Kommando erstmal rausnehmen (netter Nebeneffekt: Ich brauche nix kommentieren und kann diesen Issue schliesen) :-D

**Comment by pfichtner** [comment]
Mit 65eee3d58f1828de1e0444e556489d4e4d6b71b1 wurde UNREGISTER erstmal (bis zur Klärung) deaktiviert

**Comment by FrankR85** [comment]
Denke auch, dass mit der automatischen Deregistrierung von Clients nach 10 Timeouts das Problem großteils gelöst ist.

**Comment by mmitch** [comment]
Ja ok, das Kommando kann nach dem Timeout-Fix komplett weg – ich nehme das dann bei mir auch wieder raus.

**Comment by pfichtner** [comment]
UNREGISTER via UDP-Nachricht mit 4057c6345539b891af2aa1f1f17be13f9eb85d4e aus Server entfernt
