### ISSUE TITLE
Entfernen von NEW SEASON?

### ISSUE THREAD

**Issue by pfichtner** [fiduciagad/connected-n#28]
NEW SEASON hatten wir m.E. eingeführt, damit wir mit Clients, welche nicht mehr aktiv sind (nicht antworten), nicht permanent in Timeouts laufen (sondern nur noch beim Warten auf die Antwort von NEW SEASON). Das ist eigentlich mit #23 hinfällig. 
@FrankR85  @mmitch Sollen wir NEW SEASON/JOIN trotzdem drin lassen? Was dafür es zu behalten? Was dagegen es zu entfernen?

**Comment by FrankR85** [comment]
Ich würde es drin lassen.
Wenn wir es rausnehmen, wird ein Spieler, welcher nicht mehr aktiv ist, ja für die neue Saison noch mit ausgelost. Wenn der aber gar nicht mehr erreichbar ist, haben wir dann u.U. unnötig viele kampflose Spiele in der Saison.

Wenn man es aus diesem Winkel betrachtet, ist der `JOIN` also sehr wichtig, denn wenn der nicht beim Server ankommt, ist eine ganze Saison für den Client futsch.
Vielleicht sollte man bei `NEW SEASON` den Timeout höhersetzen?

Auch wenn es m.E. durchaus Argumente dafür gibt, würde ich es im Sinne von KISS aber vermutlich eher nicht tun.
Also: pro aktueller Zustand!

**Comment by mmitch** [comment]
Dem Client dürfte die Season recht egal sein - das ist nur ein Extrafall, den er auskodieren muss. Sonst hat er davon nichts.

Dem Betreiber des Clients (== Spieler) dürfte das in einem richtig kompetitiven Spiel nicht mehr ganz so egal sein: jeder soll gleich oft drankommen, damit das vergleichbar ist.  Wir spielen die Season ja deshalb auch bei Serverstop noch zu Ende.  (Idee: die Grafen nur bei Saisonende aktualisieren oder irgendwie vertikale Striche pro Saison einführen?)

Ich persönlich finde die Season als logische Gruppierung praktisch.  Dann ist das ganze nicht nur eine wilde Aneinanderreihung einzelner Spiele irgendwer gegen irgendwen anderen.  Darum finde ich das auch gut, dass das nach außen sichtbar ist.

**Comment by pfichtner** [comment]
Danke für das Feedback, Das sind ausreichend Argumente es drin zu lassen.
